/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addFavorite } from '../fn/favourites/add-favorite';
import { AddFavorite$Params } from '../fn/favourites/add-favorite';
import { getFavorites } from '../fn/favourites/get-favorites';
import { GetFavorites$Params } from '../fn/favourites/get-favorites';
import { isFavorite } from '../fn/favourites/is-favorite';
import { IsFavorite$Params } from '../fn/favourites/is-favorite';
import { removeFavorite } from '../fn/favourites/remove-favorite';
import { RemoveFavorite$Params } from '../fn/favourites/remove-favorite';
import { University } from '../models/university';

@Injectable({ providedIn: 'root' })
export class FavouritesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addFavorite()` */
  static readonly AddFavoritePath = '/favorites/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFavorite$Response(params: AddFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addFavorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFavorite(params: AddFavorite$Params, context?: HttpContext): Observable<void> {
    return this.addFavorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removeFavorite()` */
  static readonly RemoveFavoritePath = '/favorites/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFavorite$Response(params: RemoveFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeFavorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFavorite(params: RemoveFavorite$Params, context?: HttpContext): Observable<void> {
    return this.removeFavorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getFavorites()` */
  static readonly GetFavoritesPath = '/favorites';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFavorites()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFavorites$Response(params?: GetFavorites$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<University>>> {
    return getFavorites(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFavorites$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFavorites(params?: GetFavorites$Params, context?: HttpContext): Observable<Array<University>> {
    return this.getFavorites$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<University>>): Array<University> => r.body)
    );
  }

  /** Path part for operation `isFavorite()` */
  static readonly IsFavoritePath = '/favorites/exists/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  isFavorite$Response(params: IsFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return isFavorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isFavorite(params: IsFavorite$Params, context?: HttpContext): Observable<boolean> {
    return this.isFavorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
