/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUnreadNotificationsCount } from '../fn/notifications/get-unread-notifications-count';
import { GetUnreadNotificationsCount$Params } from '../fn/notifications/get-unread-notifications-count';
import { getUserNotifications } from '../fn/notifications/get-user-notifications';
import { GetUserNotifications$Params } from '../fn/notifications/get-user-notifications';
import { markAllAsRead } from '../fn/notifications/mark-all-as-read';
import { MarkAllAsRead$Params } from '../fn/notifications/mark-all-as-read';
import { markAsOpen } from '../fn/notifications/mark-as-open';
import { MarkAsOpen$Params } from '../fn/notifications/mark-as-open';
import { PageNotification } from '../models/page-notification';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `markAsOpen()` */
  static readonly MarkAsOpenPath = '/notifications/mark-open/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAsOpen()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsOpen$Response(params: MarkAsOpen$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAsOpen(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAsOpen$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsOpen(params: MarkAsOpen$Params, context?: HttpContext): Observable<void> {
    return this.markAsOpen$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `markAllAsRead()` */
  static readonly MarkAllAsReadPath = '/notifications/mark-all-read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAllAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead$Response(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAllAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAllAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markAllAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUnreadNotificationsCount()` */
  static readonly GetUnreadNotificationsCountPath = '/notifications/unread-count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotificationsCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotificationsCount$Response(params?: GetUnreadNotificationsCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getUnreadNotificationsCount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotificationsCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotificationsCount(params?: GetUnreadNotificationsCount$Params, context?: HttpContext): Observable<number> {
    return this.getUnreadNotificationsCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getUserNotifications()` */
  static readonly GetUserNotificationsPath = '/notifications/all-notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserNotifications$Response(params?: GetUserNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageNotification>> {
    return getUserNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserNotifications(params?: GetUserNotifications$Params, context?: HttpContext): Observable<PageNotification> {
    return this.getUserNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageNotification>): PageNotification => r.body)
    );
  }

}
