/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getQuizBySubCategory } from '../fn/quiz/get-quiz-by-sub-category';
import { GetQuizBySubCategory$Params } from '../fn/quiz/get-quiz-by-sub-category';
import { getQuizCategories } from '../fn/quiz/get-quiz-categories';
import { GetQuizCategories$Params } from '../fn/quiz/get-quiz-categories';
import { getQuizQuestions } from '../fn/quiz/get-quiz-questions';
import { GetQuizQuestions$Params } from '../fn/quiz/get-quiz-questions';
import { getQuizQuestionsByMainCategory } from '../fn/quiz/get-quiz-questions-by-main-category';
import { GetQuizQuestionsByMainCategory$Params } from '../fn/quiz/get-quiz-questions-by-main-category';
import { getSubCategoryByCategory } from '../fn/quiz/get-sub-category-by-category';
import { GetSubCategoryByCategory$Params } from '../fn/quiz/get-sub-category-by-category';
import { QuizCategory } from '../models/quiz-category';
import { QuizQuestion } from '../models/quiz-question';
import { QuizSubCategory } from '../models/quiz-sub-category';
import { saveQuizQuestion } from '../fn/quiz/save-quiz-question';
import { SaveQuizQuestion$Params } from '../fn/quiz/save-quiz-question';

@Injectable({ providedIn: 'root' })
export class QuizService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveQuizQuestion()` */
  static readonly SaveQuizQuestionPath = '/quiz';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveQuizQuestion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveQuizQuestion$Response(params: SaveQuizQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveQuizQuestion(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveQuizQuestion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveQuizQuestion(params: SaveQuizQuestion$Params, context?: HttpContext): Observable<number> {
    return this.saveQuizQuestion$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getQuizQuestions()` */
  static readonly GetQuizQuestionsPath = '/quiz/questionSet';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuizQuestions()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuizQuestions$Response(params: GetQuizQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizQuestion>>> {
    return getQuizQuestions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuizQuestions$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuizQuestions(params: GetQuizQuestions$Params, context?: HttpContext): Observable<Array<QuizQuestion>> {
    return this.getQuizQuestions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuizQuestion>>): Array<QuizQuestion> => r.body)
    );
  }

  /** Path part for operation `getQuizQuestionsByMainCategory()` */
  static readonly GetQuizQuestionsByMainCategoryPath = '/quiz/questionSetByMain';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuizQuestionsByMainCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuizQuestionsByMainCategory$Response(params: GetQuizQuestionsByMainCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizQuestion>>> {
    return getQuizQuestionsByMainCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuizQuestionsByMainCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuizQuestionsByMainCategory(params: GetQuizQuestionsByMainCategory$Params, context?: HttpContext): Observable<Array<QuizQuestion>> {
    return this.getQuizQuestionsByMainCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuizQuestion>>): Array<QuizQuestion> => r.body)
    );
  }

  /** Path part for operation `getSubCategoryByCategory()` */
  static readonly GetSubCategoryByCategoryPath = '/quiz/getSubCategory/{category_id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubCategoryByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubCategoryByCategory$Response(params: GetSubCategoryByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizSubCategory>>> {
    return getSubCategoryByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubCategoryByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubCategoryByCategory(params: GetSubCategoryByCategory$Params, context?: HttpContext): Observable<Array<QuizSubCategory>> {
    return this.getSubCategoryByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuizSubCategory>>): Array<QuizSubCategory> => r.body)
    );
  }

  /** Path part for operation `getQuizBySubCategory()` */
  static readonly GetQuizBySubCategoryPath = '/quiz/getQuizBySub/{category_id}/{subcategory_id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuizBySubCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuizBySubCategory$Response(params: GetQuizBySubCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizQuestion>>> {
    return getQuizBySubCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuizBySubCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuizBySubCategory(params: GetQuizBySubCategory$Params, context?: HttpContext): Observable<Array<QuizQuestion>> {
    return this.getQuizBySubCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuizQuestion>>): Array<QuizQuestion> => r.body)
    );
  }

  /** Path part for operation `getQuizCategories()` */
  static readonly GetQuizCategoriesPath = '/quiz/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuizCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuizCategories$Response(params?: GetQuizCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizCategory>>> {
    return getQuizCategories(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuizCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuizCategories(params?: GetQuizCategories$Params, context?: HttpContext): Observable<Array<QuizCategory>> {
    return this.getQuizCategories$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuizCategory>>): Array<QuizCategory> => r.body)
    );
  }

}
