/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getQuestions } from '../fn/rs-controller/get-questions';
import { GetQuestions$Params } from '../fn/rs-controller/get-questions';
import { getQuestionsByCategory } from '../fn/rs-controller/get-questions-by-category';
import { GetQuestionsByCategory$Params } from '../fn/rs-controller/get-questions-by-category';
import { getTop3 } from '../fn/rs-controller/get-top-3';
import { GetTop3$Params } from '../fn/rs-controller/get-top-3';
import { getTop3Sub } from '../fn/rs-controller/get-top-3-sub';
import { GetTop3Sub$Params } from '../fn/rs-controller/get-top-3-sub';
import { RsSubCategoryDto } from '../models/rs-sub-category-dto';
import { RsSubQuestionDto } from '../models/rs-sub-question-dto';
import { RsCategoryDto } from '../models/rs-category-dto';

@Injectable({ providedIn: 'root' })
export class RsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTop3Sub()` */
  static readonly GetTop3SubPath = '/api/recommenderSystem/subcategoryRecommendation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTop3Sub()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getTop3Sub$Response(params: GetTop3Sub$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RsSubCategoryDto>>> {
    return getTop3Sub(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTop3Sub$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getTop3Sub(params: GetTop3Sub$Params, context?: HttpContext): Observable<Array<RsSubCategoryDto>> {
    return this.getTop3Sub$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RsSubCategoryDto>>): Array<RsSubCategoryDto> => r.body)
    );
  }

  /** Path part for operation `getTop3()` */
  static readonly GetTop3Path = '/api/recommenderSystem/categoryRecommendation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTop3()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getTop3$Response(params: GetTop3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RsCategoryDto>>> {
    return getTop3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTop3$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getTop3(params: GetTop3$Params, context?: HttpContext): Observable<Array<RsCategoryDto>> {
    return this.getTop3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RsCategoryDto>>): Array<RsCategoryDto> => r.body)
    );
  }

  /** Path part for operation `getQuestionsByCategory()` */
  static readonly GetQuestionsByCategoryPath = '/api/recommenderSystem/categoryQuestions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuestionsByCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuestionsByCategory$Response(params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RsSubQuestionDto>>> {
    return getQuestionsByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuestionsByCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getQuestionsByCategory(params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<Array<RsSubQuestionDto>> {
    return this.getQuestionsByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RsSubQuestionDto>>): Array<RsSubQuestionDto> => r.body)
    );
  }

  /** Path part for operation `getQuestions()` */
  static readonly GetQuestionsPath = '/api/recommenderSystem/questions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuestions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestions$Response(params?: GetQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getQuestions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuestions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestions(params?: GetQuestions$Params, context?: HttpContext): Observable<{
}> {
    return this.getQuestions$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
