/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addReview } from '../fn/university-review-controller/add-review';
import { AddReview$Params } from '../fn/university-review-controller/add-review';
import { deleteReview } from '../fn/university-review-controller/delete-review';
import { DeleteReview$Params } from '../fn/university-review-controller/delete-review';
import { editReview } from '../fn/university-review-controller/edit-review';
import { EditReview$Params } from '../fn/university-review-controller/edit-review';
import { getAllReviews } from '../fn/university-review-controller/get-all-reviews';
import { GetAllReviews$Params } from '../fn/university-review-controller/get-all-reviews';
import { getUniversityRating } from '../fn/university-review-controller/get-university-rating';
import { GetUniversityRating$Params } from '../fn/university-review-controller/get-university-rating';
import { UniversityReview } from '../models/university-review';

@Injectable({ providedIn: 'root' })
export class UniversityReviewControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `editReview()` */
  static readonly EditReviewPath = '/api/reviews/editReview/{reviewId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `editReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editReview$Response(params: EditReview$Params, context?: HttpContext): Observable<StrictHttpResponse<UniversityReview>> {
    return editReview(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `editReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editReview(params: EditReview$Params, context?: HttpContext): Observable<UniversityReview> {
    return this.editReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<UniversityReview>): UniversityReview => r.body)
    );
  }

  /** Path part for operation `addReview()` */
  static readonly AddReviewPath = '/api/reviews/addReview/{universityId}/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addReview$Response(params: AddReview$Params, context?: HttpContext): Observable<StrictHttpResponse<UniversityReview>> {
    return addReview(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addReview(params: AddReview$Params, context?: HttpContext): Observable<UniversityReview> {
    return this.addReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<UniversityReview>): UniversityReview => r.body)
    );
  }

  /** Path part for operation `getUniversityRating()` */
  static readonly GetUniversityRatingPath = '/api/reviews/getRating/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUniversityRating()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUniversityRating$Response(params: GetUniversityRating$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getUniversityRating(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUniversityRating$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUniversityRating(params: GetUniversityRating$Params, context?: HttpContext): Observable<number> {
    return this.getUniversityRating$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllReviews()` */
  static readonly GetAllReviewsPath = '/api/reviews/allReviews/{universityId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllReviews()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReviews$Response(params: GetAllReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UniversityReview>>> {
    return getAllReviews(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllReviews$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReviews(params: GetAllReviews$Params, context?: HttpContext): Observable<Array<UniversityReview>> {
    return this.getAllReviews$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UniversityReview>>): Array<UniversityReview> => r.body)
    );
  }

  /** Path part for operation `deleteReview()` */
  static readonly DeleteReviewPath = '/api/reviews/deleteReview/{reviewId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteReview()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReview$Response(params: DeleteReview$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return deleteReview(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteReview$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReview(params: DeleteReview$Params, context?: HttpContext): Observable<string> {
    return this.deleteReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
