/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserQuiz } from '../../models/user-quiz';
import { UserQuizDto } from '../../models/user-quiz-dto';

export interface CreateUserQuiz$Params {
      body: UserQuizDto
}

export function createUserQuiz(http: HttpClient, rootUrl: string, params: CreateUserQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<UserQuiz>> {
  const rb = new RequestBuilder(rootUrl, createUserQuiz.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserQuiz>;
    })
  );
}

createUserQuiz.PATH = '/quiz/createUserQuiz';
