/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuizSubCategory } from '../../models/quiz-sub-category';

export interface GetSubCategoryByCategory$Params {
  category_id: number;
}

export function getSubCategoryByCategory(http: HttpClient, rootUrl: string, params: GetSubCategoryByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizSubCategory>>> {
  const rb = new RequestBuilder(rootUrl, getSubCategoryByCategory.PATH, 'get');
  if (params) {
    rb.path('category_id', params.category_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<QuizSubCategory>>;
    })
  );
}

getSubCategoryByCategory.PATH = '/quiz/getSubCategory/{category_id}';
