/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuizQuestion } from '../../models/quiz-question';

export interface GetQuizBySubCategory$Params {
  category_id: number;
  subcategory_id: number;
}

export function getQuizBySubCategory(http: HttpClient, rootUrl: string, params: GetQuizBySubCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizQuestion>>> {
  const rb = new RequestBuilder(rootUrl, getQuizBySubCategory.PATH, 'get');
  if (params) {
    rb.path('category_id', params.category_id, {});
    rb.path('subcategory_id', params.subcategory_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<QuizQuestion>>;
    })
  );
}

getQuizBySubCategory.PATH = '/quiz/{category_id}/{subcategory_id}';
