/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserQuiz } from '../../models/user-quiz';

export interface GetUserQuiz$Params {
}

export function getUserQuiz(http: HttpClient, rootUrl: string, params?: GetUserQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserQuiz>>> {
  const rb = new RequestBuilder(rootUrl, getUserQuiz.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserQuiz>>;
    })
  );
}

getUserQuiz.PATH = '/quiz/getUserQuiz';
