/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuestionSetDto } from '../../models/question-set-dto';
import { QuizQuestion } from '../../models/quiz-question';

export interface GetQuizQuestions$Params {
      body: QuestionSetDto
}

export function getQuizQuestions(http: HttpClient, rootUrl: string, params: GetQuizQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuizQuestion>>> {
  const rb = new RequestBuilder(rootUrl, getQuizQuestions.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<QuizQuestion>>;
    })
  );
}

getQuizQuestions.PATH = '/quiz/questionSet';
