/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicScore {
  academicscore_id?: number;
  intermediateScore?: number;
  matricScore?: number;
}
