/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UniversityLocation } from '../models/university-location';
import { UserLocation } from '../models/user-location';
export interface City {
  city_id?: number;
  name?: string;
  province?: string;
  universityLocations?: Array<UniversityLocation>;
  userLocations?: Array<UserLocation>;
}
