/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserLocation } from '../models/user-location';
export interface City {
  city_id?: number;
  name?: string;
  province?: string;
  userLocations?: Array<UserLocation>;
}
