/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { University } from '../models/university';
export interface Facility {
  facilityName?: string;
  facility_id?: number;
  university?: University;
}
