/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Notification {
  alertAt?: string;
  generatedAt?: string;
  message?: string;
  notification_id?: number;
  read?: boolean;
  user?: User;
}
