/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { University } from '../models/university';
export interface Notification {
  alertAt?: string;
  generatedAt?: string;
  notification_id?: number;
  open?: boolean;
  read?: boolean;
  subText?: string;
  title?: string;
  university?: University;
}
