/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizSubCategoryMainCategory } from '../models/quiz-sub-category-main-category';
export interface QuestionSubMain {
  questionSubMain_id?: number;
  quizSubCategoryMainCategory?: QuizSubCategoryMainCategory;
}
