/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizCategory } from '../models/quiz-category';
import { QuizSubCategory } from '../models/quiz-sub-category';
export interface QuizSubCategoryMainCategory {
  quizCategory?: QuizCategory;
  quizSubCategory?: QuizSubCategory;
  quizSubCategoryMainCategory_id?: number;
}
