/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizSubCategory } from '../models/quiz-sub-category';
import { UserQuiz } from '../models/user-quiz';
export interface QuizCategory {
  name?: string;
  quizSubCategories?: Array<QuizSubCategory>;
  quizcategory_id?: number;
  userQuizzes?: Array<UserQuiz>;
}
