/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RsSubQuestionDto {
  rssubcategoryid?: number;
  rssubquestion?: string;
  rssubquestionid?: number;
}
