/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityReviewRequest {
  createdDate?: string;
  lastModifiedDate?: string;
  rating?: number;
  review?: string;
}
