/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { University } from '../models/university';
import { User } from '../models/user';
export interface UniversityReview {
  rating?: number;
  review?: string;
  university?: University;
  universityreview_id?: number;
  user?: User;
}
