/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { City } from '../models/city';
export interface UniversityLocation {
  city?: City;
  latitude?: number;
  longitude?: number;
  universitylocation_id?: number;
}
