/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityFilter {
  accreditationBodies?: Array<string>;
  cities?: Array<string>;
  endDate?: string;
  maxFees?: number;
  minFees?: number;
  sectors?: Array<string>;
  startDate?: string;
}
