/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityContact {
  email?: string;
  phoneNumber?: string;
  universitycontact_id?: number;
}
