/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Facility } from '../models/facility';
import { Program } from '../models/program';
import { UniversityContact } from '../models/university-contact';
import { UniversityLocation } from '../models/university-location';
export interface University {
  about?: string;
  accrediatetionBody?: string;
  applyDate?: string;
  averageFees?: number;
  createdBy?: string;
  createdDate?: string;
  entryTestDate?: string;
  facilities?: Array<Facility>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  name?: string;
  programCount?: number;
  programs?: Array<Program>;
  rank?: number;
  startDate?: string;
  universityContacts?: Array<UniversityContact>;
  universityLocations?: Array<UniversityLocation>;
  websiteLink?: string;
}
