/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityResponse {
  about?: string;
  accrediatetionBody?: string;
  applyDate?: string;
  averageFees?: number;
  name?: string;
  rank?: number;
  startDate?: string;
  university_id?: number;
  websiteLink?: string;
}
