/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { University } from '../models/university';
export interface UniversityContact {
  email?: string;
  phoneNumber?: string;
  university?: University;
  universitycontact_id?: number;
}
