/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Program } from '../models/program';
export interface UniversityFilter {
  accreditationBodies?: Array<string>;
  cities?: Array<string>;
  endDate?: string;
  maxFees?: number;
  minFees?: number;
  program?: Array<Program>;
  sectors?: Array<string>;
  startDate?: string;
}
