/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { City } from '../models/city';
import { User } from '../models/user';
export interface UserLocation {
  city?: City;
  latitude?: string;
  longitude?: string;
  user?: User;
  userlocation_id?: number;
}
