/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicScore } from '../models/academic-score';
import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
import { UserLocation } from '../models/user-location';
export interface User {
  academicScore?: AcademicScore;
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  lastModifiedData?: string;
  lastName?: string;
  name?: string;
  password?: string;
  phoneNumber?: string;
  roles?: Array<Role>;
  userLocations?: Array<UserLocation>;
  user_id?: number;
  username?: string;
}
