/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuizCategory } from '../models/quiz-category';
import { User } from '../models/user';
export interface UserQuiz {
  completed?: number;
  date?: string;
  quizCategory?: QuizCategory;
  score?: string;
  time?: string;
  user?: User;
  userquiz_id?: number;
}
