spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:PEuXGHbXiYVhidQUUIwJfjtrYqxuFVDG@gondola.proxy.rlwy.net:10884/UniverCity}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:PEuXGHbXiYVhidQUUIwJfjtrYqxuFVDG}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Enable to see SQL errors
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:univercity.fyp@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:riiy dreg fbbm mmxv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      lifecycle-management: none

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis.railway.internal}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:fMRmravBTxbONLdbLbVAUFDrQSIGQadB}
      url: ${SPRING_DATA_REDIS_URL:redis://default:fMRmravBTxbONLdbLbVAUFDrQSIGQadB@redis.railway.internal:6379}
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: NON_NULL

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:zqr70GooivT5urALsGX3IiqeEXqSTKJ5Pz4LnnEZeCPtpUFvd7gwbNZpNCvKTOwfYJOYynNOFYi46knIW5W8YA==}
      expiration: ${JWT_EXPIRATION:31536000}
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL:http://localhost:4200/activate-account}

server:
  port: ${SERVER_PORT:8080} # Changed to standard port 8080
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:NATIVE}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL:INFO}
    org.springframework.web: DEBUG
    org.hibernate: INFO
    com.shahroz.UniverCity: DEBUG # Add this to see your application logs