spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UniverCity
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: univercity.fyp@gmail.com
    password: riiy dreg fbbm mmxv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      lifecycle-management: none

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379



  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: NON_NULL
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:9090/realms/UniverCity"
#application:
#  file:
#    uploads:
#      photos-output-path: ./uploads

application:
  security:
    jwt:
      secret-key: zqr70GooivT5urALsGX3IiqeEXqSTKJ5Pz4LnnEZeCPtpUFvd7gwbNZpNCvKTOwfYJOYynNOFYi46knIW5W8YA==
      expiration: 31536000
  mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account

server:
  port: 8088


# ----------------------------------------------------
logging:
  level.org.springframework.security: TRACE

# npm run api-gen



