/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Facility } from '../models/facility';
import { filterInstitutions } from '../fn/university/filter-institutions';
import { FilterInstitutions$Params } from '../fn/university/filter-institutions';
import { findAllUniversity } from '../fn/university/find-all-university';
import { FindAllUniversity$Params } from '../fn/university/find-all-university';
import { findUniversityById } from '../fn/university/find-university-by-id';
import { FindUniversityById$Params } from '../fn/university/find-university-by-id';
import { getFacilitiesByUniversity } from '../fn/university/get-facilities-by-university';
import { GetFacilitiesByUniversity$Params } from '../fn/university/get-facilities-by-university';
import { PageResponseUniversityResponse } from '../models/page-response-university-response';
import { saveUniversity } from '../fn/university/save-university';
import { SaveUniversity$Params } from '../fn/university/save-university';
import { searchUniversities } from '../fn/university/search-universities';
import { SearchUniversities$Params } from '../fn/university/search-universities';
import { University } from '../models/university';
import { UniversityResponse } from '../models/university-response';

@Injectable({ providedIn: 'root' })
export class UniversityService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllUniversity()` */
  static readonly FindAllUniversityPath = '/university';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllUniversity()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUniversity$Response(params?: FindAllUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUniversityResponse>> {
    return findAllUniversity(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllUniversity$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUniversity(params?: FindAllUniversity$Params, context?: HttpContext): Observable<PageResponseUniversityResponse> {
    return this.findAllUniversity$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUniversityResponse>): PageResponseUniversityResponse => r.body)
    );
  }

  /** Path part for operation `saveUniversity()` */
  static readonly SaveUniversityPath = '/university';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveUniversity()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveUniversity$Response(params: SaveUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveUniversity(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveUniversity$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveUniversity(params: SaveUniversity$Params, context?: HttpContext): Observable<number> {
    return this.saveUniversity$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findUniversityById()` */
  static readonly FindUniversityByIdPath = '/university/{university-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUniversityById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUniversityById$Response(params: FindUniversityById$Params, context?: HttpContext): Observable<StrictHttpResponse<UniversityResponse>> {
    return findUniversityById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUniversityById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUniversityById(params: FindUniversityById$Params, context?: HttpContext): Observable<UniversityResponse> {
    return this.findUniversityById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UniversityResponse>): UniversityResponse => r.body)
    );
  }

  /** Path part for operation `searchUniversities()` */
  static readonly SearchUniversitiesPath = '/university/search/{keyword}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchUniversities()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUniversities$Response(params: SearchUniversities$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<University>>> {
    return searchUniversities(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchUniversities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUniversities(params: SearchUniversities$Params, context?: HttpContext): Observable<Array<University>> {
    return this.searchUniversities$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<University>>): Array<University> => r.body)
    );
  }

  /** Path part for operation `getFacilitiesByUniversity()` */
  static readonly GetFacilitiesByUniversityPath = '/university/getFacilities/{university-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFacilitiesByUniversity()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFacilitiesByUniversity$Response(params: GetFacilitiesByUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Facility>>> {
    return getFacilitiesByUniversity(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFacilitiesByUniversity$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFacilitiesByUniversity(params: GetFacilitiesByUniversity$Params, context?: HttpContext): Observable<Array<Facility>> {
    return this.getFacilitiesByUniversity$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Facility>>): Array<Facility> => r.body)
    );
  }

  /** Path part for operation `filterInstitutions()` */
  static readonly FilterInstitutionsPath = '/university/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filterInstitutions()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterInstitutions$Response(params: FilterInstitutions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<University>>> {
    return filterInstitutions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filterInstitutions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterInstitutions(params: FilterInstitutions$Params, context?: HttpContext): Observable<Array<University>> {
    return this.filterInstitutions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<University>>): Array<University> => r.body)
    );
  }

}
