/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UniversityReview } from '../../models/university-review';
import { UniversityReviewRequest } from '../../models/university-review-request';

export interface EditReview$Params {
  reviewId: number;
      body: UniversityReviewRequest
}

export function editReview(http: HttpClient, rootUrl: string, params: EditReview$Params, context?: HttpContext): Observable<StrictHttpResponse<UniversityReview>> {
  const rb = new RequestBuilder(rootUrl, editReview.PATH, 'put');
  if (params) {
    rb.path('reviewId', params.reviewId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UniversityReview>;
    })
  );
}

editReview.PATH = '/api/reviews/editReview/{reviewId}';
