/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UniversityReview } from '../../models/university-review';

export interface GetAllReviews$Params {
  universityId: number;
}

export function getAllReviews(http: HttpClient, rootUrl: string, params: GetAllReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UniversityReview>>> {
  const rb = new RequestBuilder(rootUrl, getAllReviews.PATH, 'get');
  if (params) {
    rb.path('universityId', params.universityId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UniversityReview>>;
    })
  );
}

getAllReviews.PATH = '/api/reviews/allReviews/{universityId}';
