/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AcademicScore } from './models/academic-score';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { City } from './models/city';
export { CityDto } from './models/city-dto';
export { Facility } from './models/facility';
export { GrantedAuthority } from './models/granted-authority';
export { Notification } from './models/notification';
export { PageResponseUniversityResponse } from './models/page-response-university-response';
export { Program } from './models/program';
export { RegistrationRequest } from './models/registration-request';
export { Role } from './models/role';
export { University } from './models/university';
export { UniversityContact } from './models/university-contact';
export { UniversityFilter } from './models/university-filter';
export { UniversityLocation } from './models/university-location';
export { UniversityRequest } from './models/university-request';
export { UniversityResponse } from './models/university-response';
export { UniversityReview } from './models/university-review';
export { User } from './models/user';
export { UserLocation } from './models/user-location';
