/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {

  //local
  rootUrl: string = 'http://localhost:8080/api/v1';

  //aws
  // rootUrl: string = 'http://18.208.150.18:8088/api/v1';
  

  //railway
  // rootUrl: string = 'https://univercity-production.up.railway.app/api/v1';
  

}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
