/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AcademicScore } from './models/academic-score';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { City } from './models/city';
export type { CityDto } from './models/city-dto';
export type { Facility } from './models/facility';
export type { GrantedAuthority } from './models/granted-authority';
export type { Notification } from './models/notification';
export type { PageResponseUniversityResponse } from './models/page-response-university-response';
export  type{ Program } from './models/program';
export  type{ QuestionSetDto } from './models/question-set-dto';
export  type{ QuestionSubMain } from './models/question-sub-main';
export  type{ QuizCategory } from './models/quiz-category';
export  type{ QuizQuestion } from './models/quiz-question';
export type { QuizQuestionRequest } from './models/quiz-question-request';
export type { QuizSubCategory } from './models/quiz-sub-category';
export type { QuizSubCategoryMainCategory } from './models/quiz-sub-category-main-category';
export type { RegistrationRequest } from './models/registration-request';
export type { Role } from './models/role';
export type { University } from './models/university';
export type { UniversityContact } from './models/university-contact';
export type { UniversityFilter } from './models/university-filter';
export type { UniversityLocation } from './models/university-location';
export type { UniversityRequest } from './models/university-request';
export type { UniversityResponse } from './models/university-response';
export type { UniversityReview } from './models/university-review';
export type { User } from './models/user';
export type { UserLocation } from './models/user-location';
export type { UserQuiz } from './models/user-quiz';
export type { UserQuizDto } from './models/user-quiz-dto';
