/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UniversityService } from './services/university.service';
export { AuthenticationService } from './services/authentication.service';
