/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserService } from './services/user.service';
export { NotificationsService } from './services/notifications.service';
export { UniversityReviewControllerService } from './services/university-review-controller.service';
export { WhatsappControllerService } from './services/whatsapp-controller.service';
export { UniversityService } from './services/university.service';
export { QuizService } from './services/quiz.service';
export { FavouritesService } from './services/favourites.service';
export { AuthenticationService } from './services/authentication.service';
export { UniversityFilterService } from './services/university-filter.service';
