/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RsSubQuestionDto } from '../../models/rs-sub-question-dto';

export interface GetQuestionsByCategory$Params {
      body: {
[key: string]: {
};
}
}

export function getQuestionsByCategory(http: HttpClient, rootUrl: string, params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RsSubQuestionDto>>> {
  const rb = new RequestBuilder(rootUrl, getQuestionsByCategory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RsSubQuestionDto>>;
    })
  );
}

getQuestionsByCategory.PATH = '/api/recommenderSystem/categoryQuestions';
