/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Facility } from '../../models/facility';

export interface GetFacilitiesByUniversity$Params {
  'university-id': number;
}

export function getFacilitiesByUniversity(http: HttpClient, rootUrl: string, params: GetFacilitiesByUniversity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Facility>>> {
  const rb = new RequestBuilder(rootUrl, getFacilitiesByUniversity.PATH, 'get');
  if (params) {
    rb.path('university-id', params['university-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Facility>>;
    })
  );
}

getFacilitiesByUniversity.PATH = '/university/getFacilities/{university-id}';
