/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UniversityLocation } from '../../models/university-location';

export interface GetUniversityLocation$Params {
  'university-id': number;
}

export function getUniversityLocation(http: HttpClient, rootUrl: string, params: GetUniversityLocation$Params, context?: HttpContext): Observable<StrictHttpResponse<UniversityLocation>> {
  const rb = new RequestBuilder(rootUrl, getUniversityLocation.PATH, 'get');
  if (params) {
    rb.path('university-id', params['university-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UniversityLocation>;
    })
  );
}

getUniversityLocation.PATH = '/university/getUniversityLocation/{university-id}';
